import Link from "next/link";
import AuthFormHoc from "../_components/auth.form.hoc";
import clsx from "clsx";
import { major_mono, plex_mono } from "../_utils/fonts";
import LoginForm from "./_components/LoginForm";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sign In",
  description: "Generated by create next app",
};

type Props = {};
export default function SignIn({}: Props) {
  return (
    <AuthFormHoc title="Login">
      <LoginForm />
      <div className={clsx(major_mono.className, "divider")}>OR</div>
      <div className="flex flex-col items-start gap-2">
        <Link href={"/sign-up"} className={clsx(plex_mono.className)}>
          Sign up
        </Link>
        <Link href={"/forgot_password"} className={clsx(plex_mono.className)}>
          Forgot password
        </Link>
      </div>
    </AuthFormHoc>
  );
}
